### ISSUE TITLE
Adding github as a gem source raises error

### ISSUE THREAD

**Issue by protocarl** [wycats/bundler#33] opened 2009-07-31 03:21 UTC
When github is added as a source, an error is raised:

```
$ cat Gemfile
source 'http://gems.github.com'

gem 'nokogiri'

$ gem bundle
Updating source: http://gems.rubyforge.org
Updating source: http://gems.github.com
ERROR:  While executing gem ... (ArgumentError)
    comparison of String with 3 failed
```

However, without github, it works as advertised:
    $ cat Gemfile
    gem 'nokogiri'

```
$ gem bundle
Updating source: http://gems.rubyforge.org
Calculating dependencies...
Downloading nokogiri-1.3.3.gem
Installing nokogiri-1.3.3.gem
Building native extensions.  This could take a while...
Done.
```

**Comment by jsmestad** [comment] 2009-07-31 05:19
I have this same error.

**Comment by halorgium** [comment] 2009-08-08 10:15
This is a duplicate of #18

**Closed as completed** 2009-08-17 18:45 UTC
